#filebeat7.8.0
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/filebeat_logs/*.log
  json.keys_under_root: true
  json.overwrite_keys: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  #host: "localhost:5601"

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://elasticsearch_test.xxx.com:9200"]
  indices:
    - index: "twtest-log-error-%{+yyyy.MM}"
      when.equals:
        level: "error"
    - index: "twtest2-log-all-%{+yyyy.MM}"
      not:
        when.equals:
          level: "error"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
